name: PUBLISH DOCS
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["RELEASE AND PUBLISH"]
    types:
      - completed
  # or set up your own custom triggers
permissions:
  contents: write # allows the 'Deploy' step without tokens

jobs:
  get_history:
    runs-on: ubuntu-latest
    steps:
    - name: get the gh-pages repo
      uses: actions/checkout@v3
      with:
        ref: gh-pages

    - name: create a document artifact
      uses: actions/upload-artifact@v3
      with:
        name: documentation
        path: ./docs


  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout src # checks out the source code into the active workspace
        uses: actions/checkout@v3

      - name: Download the existing documents artifact
      - run: mkdir -p ./docs
        uses: actions/download-artifact@v3
        with:
          name: documentation
          path: ./docs
      - run: ls -R

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci # installs npm packages
      - run: npm run build # set up 'build' script in your package.json

      - name: Build documents
        run: npm run docs #set up 'docs' build script in your package.json

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs          # take the 'docs' folder in the current workspace
          target-folder: docs   # and put it's content in the 'docs' folder of gh-pages 