name: RELEASE
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Build
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'npm'
      - run: npm ci
      - run: npm run build

      - name: Make build artifact
        run: npm pack ./dist

      - name: Get Package Version
        run: |
          echo "RELEASE_NAME=$(npm info ./ version)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          tag_name: ${{ env.RELEASE_NAME }}
          files: typedoc-plugin-versions-*.tgz


