name: RELEASE AND PUBLISH
on:
  workflow_dispatch:
jobs:
  test:
    name: Test and Build
    uses: ./.github/workflows/test.yml

  release:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Make build artifact
        run: npm pack ./dist

      - name: Get Package Version
        run: |
          echo "RELEASE_NAME=$(npm info ./ version)" >> $GITHUB_ENV

      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          prerelease: false
          generate_release_notes: true
          tag_name: ${{ env.RELEASE_NAME }}
          files: typedoc-plugin-versions-*.tgz


