name: TEST AND BUILD
on:
  workflow_dispatch:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 15.x, 16.x]
    steps:
      - uses: actions/checkout@v3

      - name: Test with Node ${{matrix.node-version}}
        uses: actions/setup-node@v3
        with:
          node-version: ${{matrix.node-version}}
          cache: 'npm'
      - run: | 
          npm ci
          npm run build
          npm run test

      - name: Upload coverage artifact
        if: matrix.node-version == '16.x'
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: ./test/coverage/clover.xml

      - name: Upload build as artifact
        if: matrix.node-version == '16.x'
        uses: actions/upload-artifact@v3
        with:
          name: distribution
          path: ./dist

