name: Test
on:
    workflow_dispatch:
    workflow_call:
    pull_request:
        branches:
            - '*'
    push:
        branches:
            - '*'
jobs:
    build:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [lts/*, latest]
        steps:
            - uses: actions/checkout@v4

            - name: Test with Node ${{matrix.node-version}}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{matrix.node-version}}
                  cache: npm
            - run: |
                  npm ci
                  npm run build
                  npm run test

            - name: Upload coverage artifact
              if: matrix.node-version == 'lts/*'
              uses: actions/upload-artifact@v4
              with:
                  name: coverage
                  path: ./test/coverage/clover.xml

            - name: Upload build artifact
              if: matrix.node-version == 'lts/*'
              uses: actions/upload-artifact@v4
              with:
                  name: distribution
                  path: ./dist
